// <auto-generated />
using System;
using HospitalAppointment.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalAppointment.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalAppointment.API.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Email = "admin@hospital.com",
                            FullName = "System Admin",
                            Password = "admin123"
                        },
                        new
                        {
                            AdminId = 2,
                            Email = "superadmin@hospital.com",
                            FullName = "Super Admin",
                            Password = "super123"
                        });
                });

            modelBuilder.Entity("HospitalAppointment.API.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HospitalAppointment.API.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Email = "cardio1@hospital.com",
                            FullName = "Dr. Ajit Sharma",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000001",
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            Email = "cardio2@hospital.com",
                            FullName = "Dr. Rohan Patil",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000002",
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 3,
                            Email = "cardio3@hospital.com",
                            FullName = "Dr. Shreya Agarwal",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000003",
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 4,
                            Email = "neuro1@hospital.com",
                            FullName = "Dr. Siddhat Nikam",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000004",
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 5,
                            Email = "neuro2@hospital.com",
                            FullName = "Dr. Manisha Joshi",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000005",
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 6,
                            Email = "neuro3@hospital.com",
                            FullName = "Dr. Sanket Kulkarni",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000006",
                            SpecializationId = 2
                        },
                        new
                        {
                            DoctorId = 7,
                            Email = "ortho1@hospital.com",
                            FullName = "Dr. Abhishek Narkhede",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000007",
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 8,
                            Email = "ortho2@hospital.com",
                            FullName = "Dr. Atharva Ingle",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000008",
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 9,
                            Email = "ortho3@hospital.com",
                            FullName = "Dr. Shruti Patil",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000009",
                            SpecializationId = 3
                        },
                        new
                        {
                            DoctorId = 10,
                            Email = "derma1@hospital.com",
                            FullName = "Dr. Vaibhav Kamble",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000010",
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 11,
                            Email = "derma2@hospital.com",
                            FullName = "Dr. Vijay Chavan",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000011",
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 12,
                            Email = "derma3@hospital.com",
                            FullName = "Dr. Sakshi Salve",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000012",
                            SpecializationId = 4
                        },
                        new
                        {
                            DoctorId = 13,
                            Email = "gm1@hospital.com",
                            FullName = "Dr. GM One",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000013",
                            SpecializationId = 5
                        },
                        new
                        {
                            DoctorId = 14,
                            Email = "gm2@hospital.com",
                            FullName = "Dr. GM Two",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000014",
                            SpecializationId = 5
                        },
                        new
                        {
                            DoctorId = 15,
                            Email = "gm3@hospital.com",
                            FullName = "Dr. GM Three",
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "900000015",
                            SpecializationId = 5
                        });
                });

            modelBuilder.Entity("HospitalAppointment.API.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HospitalAppointment.API.Models.PatientHealthHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiseaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientHealthHistories");
                });

            modelBuilder.Entity("HospitalAppointment.API.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            SpecializationId = 2,
                            Name = "Neurology"
                        },
                        new
                        {
                            SpecializationId = 3,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            SpecializationId = 4,
                            Name = "Dermatology"
                        },
                        new
                        {
                            SpecializationId = 5,
                            Name = "General Medicine"
                        });
                });

            modelBuilder.Entity("HospitalAppointment.API.Models.Doctor", b =>
                {
                    b.HasOne("HospitalAppointment.API.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("HospitalAppointment.API.Models.PatientHealthHistory", b =>
                {
                    b.HasOne("HospitalAppointment.API.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalAppointment.API.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
